services:
  nestjs-app:
    container_name: nestjs-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - ./prisma:/app/prisma
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
